https://iamtrask.github.io/2015/07/12/basic-python-network/

In [23]:
#Dependencies
import numpy as np

In [25]:
#Input and Output
x=np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T

In [27]:
#Synpases / Weights Initialization
syn0=2*np.random.random((3,4)) - 1
syn1=2*np.random.random((4,1)) - 1
print("Initial synapses ",end='\n\n')
print(syn0,syn1,end='\n',sep='\n\n')



Initial synapses 

[[ 0.42854107 -0.95015365  0.21948018  0.07377262]
 [ 0.31893524  0.23530716  0.41449766 -0.68507551]
 [ 0.84760832 -0.65517271  0.12519385  0.9571083 ]]

[[-0.88461816]
 [-0.77776684]
 [-0.68741362]
 [-0.2413986 ]]


In [29]:
try:
    for i in range(60000):
        L1=1/(1+ np.exp(-np.dot(x,syn0)))
        L2=1/(1+ np.exp(-np.dot(L1,syn1)))

        #Backpropagation
        l2_delta= (y-L2)*(L2*(1-L2))
        l1_delta= l2_delta.dot(syn1.T)* (L1*(1-L1))

        #Weight updation
        syn1+=L1.T.dot(l2_delta)
        syn0+=x.T.dot(l1_delta)
    print("Training Complete")

except Exception as e:
    print("Trained upto epochs: ",i)

Training Complete


In [32]:
print("Synapses after training ",end='\n\n')
print(syn0,syn1,end='\n',sep='\n\n')

Synapses after training 

[[ 1.63635026 -7.2296919   0.20773408 -5.57538814]
 [-0.836702   -7.16696901  1.45274509 -5.69180537]
 [ 1.29045422  3.09786383 -0.40128328  8.48914423]]

[[ -3.82358721]
 [-13.92675463]
 [ -3.87097779]
 [ 12.0210549 ]]
